// Auto-generated by scripts/generate-build-info.js
// Do not edit this file manually

export const BUILD_INFO = {
  "appName": "matcha-auth",
  "version": "2.5.9",
  "environment": "Capacitor/Android",
  "ProjectUrl": "https://github.com/Hill-1024/matcha-auth",
  "buildTime": "2026/6/9 23:28:12",
  "description": "A Material You styled 2FA Token Authenticator"
};
